### ISSUE TITLE
Upcoming change in `ggplot2:::titleGrob()`

### ISSUE THREAD

**Issue by teunbrand** [wilkelab/ggtext#101]
Hi Claus and Brenton,

This issue is just a heads up that in the dev version of ggplot2, the `titleGrob()` has been [refactored](https://github.com/tidyverse/ggplot2/pull/5273).
In particular, the function in ggtext's [R/add-margins.R](https://github.com/wilkelab/ggtext/blob/50fdaba101b2c591c08e9d67782a5b86621a4fa9/R/add-margins.R) might have become obsolete.
I tried to see if any visual tests had broken, but wasn't able to verify due to a vdiffr version difference.
By eye, nothing *looks* wrong, but it might be not the worst idea to double-check yourselves against ggplot2's dev version at some point.
Feel free to close this issue if all is behaving as expected.

**Comment by clauswilke** [comment]
As far as I can tell (and remember), the code paths in ggtext are entirely independent of `titleGrob()` in ggplot2. So any changes there should not affect ggtext, unless some very fundamental changes were introduced into how text elements work in themes, and I don't think is the case. So I wouldn't expect any problems, but a check wouldn't hurt.

@bwiernik Are you willing to go through the visual tests and make sure they all look correct with the development version of ggplot2?

**Comment by bwiernik** [comment]
Sure

**Comment by teunbrand** [comment]
I tested with the dev version of ggplot2 and all appears to be fine, so I'll go ahead and close this.
