### ISSUE TITLE
Including arrows in axis text using `element_markdown()`

### ISSUE THREAD

**Issue by StefanVermeent** [wilkelab/ggtext#103]
library(ggplot2)
library(ggtext)

I was wondering if there is any way to include left/right arrows (i.e., "&larr;", "&rarr;") in either axis titles or text using `element_markdown()`.

If I try the code below, it removes the text of the arrow while retaining text with plain text.

```r
data <- data.frame(
  x = c(rep("&larr;", 20), rep("B", 10))
  ) 

ggplot(data, aes(x = x)) +
  geom_bar() +
  theme(
    axis.text.x = element_markdown()
  )
```

**Comment by teunbrand** [comment]
The example you've shared seems to work as intended, no?

``` r
library(ggtext)
library(ggplot2)

data <- data.frame(
  x = c(rep("&larr;", 20), rep("B", 10))
) 

ggplot(data, aes(x = x)) +
  geom_bar() +
  theme(
    axis.text.x = element_markdown()
  )
```

![](https://i.imgur.com/hezqjhB.png)

An alternative could be to use the unicode symbol for arrows (`\u2190` for left, `\u2192` for right)

``` r
last_plot() %+% data.frame(
  x = c(rep("\u2190", 20), rep("B", 10))
)
```

![](https://i.imgur.com/e2IK4Et.png)

<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
In general I would recommend using the Unicode escapes like shown above. Those will work in regular `element_text()` as well
