### ISSUE TITLE
Is it possible to have both a subscript and superscript on the same character?

### ISSUE THREAD

**Issue by mdsdossant** [wilkelab/ggtext#104]
I tried things like, e.g., 

`"<sub>*x*<sup>2</sup>j<sub>"`

**Comment by bwiernik** [comment]
Yes, the 2 there will be slightly smaller and lower compared to if it were a superscript not also wrapped in subscript 

![image](https://github.com/wilkelab/ggtext/assets/4773225/388ca4ee-78cb-4e2a-ae81-4b6864c4df38)
