### ISSUE TITLE
Multiple consecutive spaces are collapsed to one space in ggtext::element_markdown

### ISSUE THREAD

**Issue by Close-your-eyes** [wilkelab/ggtext#106]
Dear all,

I noted that when I supply an axis text or axis title or whatever with ggtext::element_markdown, then muliple consecutive spaces are reduced to one space only.

Is that an expected behaviour?

**Comment by bwiernik** [comment]
This is expected behavior. The Markdown spec calls for consecutive spaces to be collapsed to 1. You can enter `&nbsp;` to enter a non-breaking space character, which will be preserved.

**Comment by Close-your-eyes** [comment]
Very nice. Thank you.
