### ISSUE TITLE
element_markdown fails when y axis is moved to the right

### ISSUE THREAD

**Issue by jarekbryk** [wilkelab/ggtext#108]
Hi, 

I have observed a strange behaviour when working with plots with y axis on the right (`scale_y_continuous(position = "right")`). element_markdown formatting works fine on axis title when the axis is on the left of the plot, but markdown is not rendered when the axis is moved to the right. Is this a bug or am I missing something?

Thanks,
Jarek

``` r
library(tidyverse)
library(ggtext)

# Works fine
mtcars %>% 
    ggplot() + aes(x = mpg, y = cyl) + geom_point() +
    labs(y = "Number of <sup>cylinders</sup>") +
    theme(axis.title.y = element_markdown())
```

![](https://i.imgur.com/0tQjszx.png)

``` r

# Fails
mtcars %>% 
    ggplot() + aes(x = mpg, y = cyl) + geom_point() +
    scale_y_continuous(position = "right") +
    labs(y = "Number of <sup>cylinders</sup>") +
    theme(axis.title.y = element_markdown())
```

![](https://i.imgur.com/rgjrVZw.png)

<sup>Created on 2023-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
Use `theme(axis.title.y.right = element_markdown())`

**Comment by jarekbryk** [comment]
🤦🏻‍♀️ Thank you!

**Comment by bwiernik** [comment]
No problem--it's super confusing. Based on the parameter names, I would expect `axis.title.y` and `axis.title.x` to apply to both sides, but they only apply to the left and bottom.
