### ISSUE TITLE
not all unicode symbols work (for example: \u25a0)

### ISSUE THREAD

**Issue by Laurent-Smeets-GSS-Account** [wilkelab/ggtext#118]
For example, the Unicode symbol for a filled square (https://www.unicode.org/charts/nameslist/n_25A0.html), does not work properly in  `geom_richtext()`.  This would be convenient to draw a legend as part of a label. 

```
library(ggplot2)
library(ggtext)

df <- data.frame(
  label = c("<span style = 'color:red;'>text  \u00A9</span>", # works
            "<span style = 'color:red;'>text \u03bc</span>", # works
            "<span style = 'color:red;'>text  \u25a0</span>"), # does not work
  x = 1,
  y = 3:1,
  stringsAsFactors = FALSE
)


ggplot(NULL, aes(x, y, label = label)) +
  geom_richtext(data = df) +
  xlim(0, 2)

```

**Comment by bwiernik** [comment]
That renders a red square on my system. What exactly isn't working?

**Comment by clauswilke** [comment]
If specific symbols don't render that's usually a problem with the graphics device used or alternatively the font.

``` r
library(ggplot2)
library(ggtext)

df <- data.frame(
  label = c("<span style = 'color:red;'>text  \u00A9</span>", # works
            "<span style = 'color:red;'>text \u03bc</span>", # works
            "<span style = 'color:red;'>text  \u25a0</span>"), # does not work
  x = 1,
  y = 3:1,
  stringsAsFactors = FALSE
)


ggplot(NULL, aes(x, y, label = label)) +
  geom_richtext(data = df) +
  xlim(0, 2)
```

![](https://i.imgur.com/Uz1AegD.png)

<sup>Created on 2024-09-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Laurent-Smeets-GSS-Account** [comment]
very strange. for me it  rendered a very large box without any content. but I restarted my system and now it works. sorry for this. If I can find a way to replicate the error I will reopen
