### ISSUE TITLE
Add support to all basic Markdown syntax elements and fix superscript-related issue

### ISSUE THREAD

**Issue by GegznaV** [wilkelab/ggtext#12]
As a user, I expect **all** basic Markdown syntax (see bullets 1, 2, and 3 below) to be supported correctly. Making new lines, bold, and italic text as well as escaping symbols (`\* \_" \^ \~ \\ $`) works as expected.

But there are the following issues:

1) Superscript tags do not close correctly (see examples below).
2) Making subscripts, endashes, and emdashes does not work at all (see examples below).
3) If I try to make verbatim code and strikethrough text, the error messages state that tags `<code>` and `<del>` are not supported (see examples below). Most probably, it's an issue in **gridtext** package.
4) There is an issue in rendering LaTeX equations, but as understood, work is in progress (#4).

The examples of issues in rendering Markdown syntax elements
(sorry for the large images: I'm not sure how to control the size of them with **reprex**)
``` r
library(ggplot2)
library(ggtext)


gg_example <- function(str) {
  ggplot() +
  ggtitle(str) +
  theme(plot.title = element_markdown(lineheight = 1.1))
}
```

``` r
# NOT OK (does not close correctly)
gg_example("normal ^superscript^ normal")
```

![](https://i.imgur.com/TpW4KHd.png)

``` r
# NOT OK (does not close correctly)
gg_example("Length (cm^2^)")
```

![](https://i.imgur.com/N4BBAXw.png)

``` r
# Does not work:
gg_example("normal ~subscript~ normal")
```

![](https://i.imgur.com/iKGPmL6.png)

``` r
# Does not work:
gg_example("(CO~2~) ")
```

![](https://i.imgur.com/44LASNZ.png)

``` r
# Does not work:
gg_example("endash: --")
```

![](https://i.imgur.com/IbR2BiI.png)

``` r
# Does not work:
gg_example("emdash: ---")
```

![](https://i.imgur.com/aGzKzQs.png)

``` r
# Not OK (not interpreted as Equation):
gg_example("equation: $A = \\pi*r^{2}$")
```

![](https://i.imgur.com/4bi89uz.png)

``` r

# Error
gg_example("normal `verbatim code` normal")
#> Error: gridtext has encountered a tag that isn't supported yet: <code>
#> Only a very limited number of tags are currently supported.

# Error
gg_example("normal ~~strikethrough~~ normal")
#> Error: gridtext has encountered a tag that isn't supported yet: <del>
#> Only a very limited number of tags are currently supported.
```

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The examples of code with Markdown syntax elements that are rendered as expected.

```r
# OK
gg_example(
"End a line with two spaces  
to start a new paragraph."
)

# OK
gg_example("normal *italics* normal")
gg_example("normal _italics_ normal")

# OK
gg_example("normal **bold** normal")  
gg_example("normal __bold__ normal") 

# OK
gg_example("normal **_bold italics_** normal")  

# OK
gg_example("escaped: \\*")
gg_example("escaped: \\_")
gg_example("escaped: \\^")
gg_example("escaped: \\~")
gg_example("escaped: \\\\")
gg_example("escaped: \\$")
```

**Comment by clauswilke** [comment]
This is a gridtext issue.

**Comment by kongdd** [comment]
Just wondering whether `gridtext` has plan to support this feature?

**Comment by kongdd** [comment]
This my solution for superscript and subscript. 
Hope that helps.

```R
#' @importFrom stringr str_replace_all
#' @export
str_mk <- function(x) {
    replacement <- c(
        "(\\^\\{?)([\\w\\+\\-\\*\\\\]*)(\\}?)" = "<sup>\\2</sup>",
        "(\\_\\{?)([\\w\\+\\-\\*\\\\]*)(\\}?)" = "<sub>\\2</sub>",
        "\n" = "<br>"
    )
    str_replace_all(x, replacement)
}

x = c(
    "gC m^{-2} d^{-1}",
    "gC m^-2 d^-1",
    "gC m_{-2} d_{-1}",
    "gC m_-2 d_-1", 
    "gC \n mm/d"
)
str_mk(x)
#> [1] "gC m<sup>-2</sup> d<sup>-1</sup>" "gC m<sup>-2</sup> d<sup>-1</sup>"
#> [3] "gC m<sub>-2</sub> d<sub>-1</sub>" "gC m<sub>-2</sub> d<sub>-1</sub>"
#> [5] "gC <br> mm/d"
```
<https://rpkgs.github.io/gg.layers/reference/str_mk.html>
