### ISSUE TITLE
Error in (angle %||% 0)%%360 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by awconway** [wilkelab/ggtext#13]
On a fresh install of ggtext I get this error with the example from the readme:

Error in (angle %||% 0)%%360 : non-numeric argument to binary operator

Tried a simplified version of the example from the readme (shown below) and got the same error. Tested on macOS and Linux. 

```r
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_point(size = 3) +
  labs(
    title = "**Fisher's *Iris* dataset**",
    x = "Sepal length (cm)", y = "Sepal width (cm)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_markdown(lineheight = 1.1),
    legend.text = element_markdown(size = 11)
  )
```

My colleague is getting the same error on his system.

Thanks very much for the package - looks great.

─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Catalina 10.15.1      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_CA.UTF-8                 
 ctype    en_CA.UTF-8                 
 tz       America/Toronto             
 date     2020-01-31                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                          
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                  
 backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.0)                  
 callr         3.3.1      2019-07-18 [1] CRAN (R 3.6.0)                  
 cli           2.0.1      2020-01-08 [1] CRAN (R 3.6.1)                  
 colorspace    1.4-1      2019-03-18 [1] CRAN (R 3.6.0)                  
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                  
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                  
 devtools    * 2.1.0      2019-07-06 [1] CRAN (R 3.6.0)                  
 digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.0)                  
 dplyr         0.8.3      2019-07-04 [1] CRAN (R 3.6.0)                  
 fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.0)                  
 farver        2.0.3      2020-01-16 [1] CRAN (R 3.6.0)                  
 fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                  
 ggplot2     * 3.2.1      2019-08-10 [1] CRAN (R 3.6.0)                  
 ggtext      * 0.1.0      2020-01-31 [1] Github (wilkelab/ggtext@3b25fca)
 glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                  
 gridtext    * 0.1.0      2020-01-24 [1] CRAN (R 3.6.0)                  
 gtable        0.3.0      2019-03-25 [1] CRAN (R 3.6.0)                  
 labeling      0.3        2014-08-23 [1] CRAN (R 3.6.0)                  
 lazyeval      0.2.2      2019-03-15 [1] CRAN (R 3.6.0)                  
 lifecycle     0.1.0      2019-08-01 [1] CRAN (R 3.6.0)                  
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                  
 markdown      1.1        2019-08-07 [1] CRAN (R 3.6.0)                  
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                  
 munsell       0.5.0      2018-06-12 [1] CRAN (R 3.6.0)                  
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.6.0)                  
 pillar        1.4.3      2019-12-20 [1] CRAN (R 3.6.0)                  
 pkgbuild      1.0.4      2019-08-05 [1] CRAN (R 3.6.0)                  
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.0)                  
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                  
 prettyunits   1.1.0      2020-01-09 [1] CRAN (R 3.6.0)                  
 processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.0)                  
 ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                  
 purrr         0.3.3      2019-10-18 [1] CRAN (R 3.6.0)                  
 R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.0)                  
 Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.0)                  
 remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                  
 rlang         0.4.2      2019-11-23 [1] CRAN (R 3.6.0)                  
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                  
 rstudioapi    0.10       2019-03-19 [1] CRAN (R 3.6.0)                  
 scales        1.1.0      2019-11-18 [1] CRAN (R 3.6.0)                  
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                  
 stringi       1.4.5      2020-01-11 [1] CRAN (R 3.6.0)                  
 stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                  
 testthat      2.2.1      2019-07-25 [1] CRAN (R 3.6.0)                  
 tibble        2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                  
 tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.6.0)                  
 usethis     * 1.5.1.9000 2019-08-19 [1] Github (r-lib/usethis@bcef417)  
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                  
 xml2          1.2.2      2019-08-09 [1] CRAN (R 3.6.1)

**Comment by clauswilke** [comment]
You need the development version of ggplot2 (`remotes::install_github("tidyverse/ggplot2")`). It should have pulled that in automatically when you installed ggtext, but apparently that didn't happen.
