### ISSUE TITLE
Error in (angle %||% 0)%%360 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by EuanDewar** [wilkelab/ggtext#14]
Getting the error

Error in (angle %||% 0)%%360 : non-numeric argument to binary operator

Whenever I try to use the element_markdown() function in any plot. I've tried copying the examples with the iris dataset directly and get the same issue. 

I'm on the latest version of R and ggplot.

Thanks.

**Comment by clauswilke** [comment]
Please see #13.

**Comment by adrzell** [comment]
I am having the same issue, even after following the instructions in #13 - I uninstalled ggplot2, then re-installed it using the remotes::install_github("tidyverse/ggplot2") code. 
Really great package - looking forward to getting it working!

**Comment by clauswilke** [comment]
Make sure you restart R after installing ggplot2. Then, if the problem persists, please run `sessionInfo()` after loading ggplot2 and let me know which version it reports.

**Comment by adrzell** [comment]
It is working now - thanks for the tip to a rookie. I feel more successful than whichever team wins the super bowl. Thanks!
