### ISSUE TITLE
element_textbox_simple ignores hjust

### ISSUE THREAD

**Issue by eipi10** [wilkelab/ggtext#17]
In trying out `ggtext` I found that `element_textbox_simple` is ignoring the `hjust` argument. Here's an example in which I tried to center the title, but it is still left-justified. On the other hand, `element_textbox` centers the title correctly. Also note, that `element_textbox_simple` fills the entire title strip, while `element_textbox` fills only the horizontal extent of the title text. I'm not sure if this is the intended behavior. I'm using version 0.1.0 of ggtext (SHA1: 3b25fcaa).

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  labs(title="this is the title") +
  theme(plot.title=element_textbox_simple(fill="red", hjust=0.5))
```

![](https://i.imgur.com/mLAzR5j.png)

``` r

ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  labs(title="this is the title") +
  theme(plot.title=element_textbox(fill="red", hjust=0.5))
```

![](https://i.imgur.com/gHNhWr9.png)

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Both behaviors are as designed. Note that `hjust` governs the alignment of the textbox relative to the enclosing space, and `halign` governs the horizontal alignment inside the textbox. `element_textbox_simple()` sets the width to span the entire available horizontal space, therefore `hjust` doesn't seem to have an effect. But `halign` works. Similarly, if you explicitly set the width to not span the entire space, you see that `hjust` works.

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  labs(title="this is the title") +
  theme(plot.title=element_textbox_simple(fill="red", halign=0.5))
```

![](https://i.imgur.com/zhQxfVQ.png)


``` r
ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  labs(title="this is the title") +
  theme(plot.title=element_textbox_simple(fill="red", hjust=0.5, width = NULL))
```

![](https://i.imgur.com/FO3gZM1.png)

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you just want a label with a colored background, you should probably use `element_markdown()`. `element_textbox_simple()` is specifically meant for longer text that requires word wrapping, in which case the default settings make sense.

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) + 
  geom_point() + 
  labs(title="this is the title") +
  theme(plot.title=element_markdown(fill="red", hjust=0.5))
```

![](https://i.imgur.com/3PV9P9a.png)

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eipi10** [comment]
Got it. Thanks! Sorry to have bothered you.
