### ISSUE TITLE
ggtext has conflicts with ggdag

### ISSUE THREAD

**Issue by njsilbiger** [wilkelab/ggtext#23]
Hello,
I have been trying to implement titles in my DAGS that use ggtext, but it seems there is a conflict because ggtext is dependent on the github version of ggplot (which then doesn't allow me to make a ggdag plot).  Is it possible to have ggtext use the CRAN version of ggplot to minimize conflicts with other packages that are not yet compatible with the github version of ggplot?

Thank you!

**Comment by clauswilke** [comment]
ggtext requires ggplot2 version 3.3.0 or later. Otherwise it doesn't work. (See e.g. #13, #14, #21.) Version 3.3.0 should get released on CRAN soon.
