### ISSUE TITLE
element_markdown error

### ISSUE THREAD

**Issue by meersel** [wilkelab/ggtext#25]
After installation of the new ggplot2 version 3.3.0 (CRAN), the  ggtext::element_markdown() function does not work anymore. It produces the following error message:

**Error in richtext_grob(label, x = x, y = y, hjust = hj, vjust = vj, halign = halign, : unused arguments (halign = halign, valign = valign)**

7. element_grob.element_markdown(el, ...)
6. element_grob(el, ...)
5. element_render(theme, "plot.title", plot$labels$title, margin_y = TRUE)
4. ggplot_gtable.ggplot_built(data)
3. ggplot_gtable(data)
2. print.ggplot(x)
1. function (x, ...) UseMethod("print")(x)

------

Brief description of the problem or desired feature.

```r
# insert reprex here
```

**Comment by clauswilke** [comment]
Your ggtext and gridtext packages are out of synch. My best guess is installing ggplot2 installed the latest version of gridtext, but you're running an old version of ggtext. Install the latest version of everything and things should be fine.
