### ISSUE TITLE
How to italicize a single word in a ggplot title that is passed as a variable to a function?

### ISSUE THREAD

**Issue by DeFilippis** [wilkelab/ggtext#28]
Let's say I have the following function where I pass a dataframe and a variable name:

```
plot_breaks <- function(data, dv){
 ggplot(data = data, aes(x = date, y = dv)) + 
    geom_line() +
    ggtitle(paste("Time Series of ", dv)) +
    xlab("Date") 
}
```

I want to italicize the string passed as part of the `dv` variable.  How would I do this in ggtext?

**Comment by clauswilke** [comment]
This question would be better suited to a general-purpose discussion board, such as stackoverflow.com.
