### ISSUE TITLE
Unable to install - Error: Failed to install 'ggtext' from GitHub

### ISSUE THREAD

**Issue by DesmondChoy** [wilkelab/ggtext#29]
Hello,

After running 
```
remotes::install_github("wilkelab/ggtext")
``` 
I'm getting the following error:
```
Error: Failed to install 'ggtext' from GitHub:
  (converted from warning) unable to access index for repository https://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6:
  cannot open URL 'https://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6/PACKAGES'
```

Could you advise how I might be able to resolve this? Thank you.

**Comment by clauswilke** [comment]
This error doesn't make a lot of sense to me. It's most likely during the installation of the required dependencies. Can you try to install them separately, with `install.packages()`? It's all the packages listed here (except "grid", which comes with R):
https://github.com/wilkelab/ggtext/blob/24e9cd059e599e1ce39bfaf3951d09cccc0aad99/DESCRIPTION#L20-L24

**Comment by DesmondChoy** [comment]
Yes you're right - installed the dependencies separately, and ggtext was subsequently installed successfully :) Thank you!
