### ISSUE TITLE
A problem with "ggtext" installation

### ISSUE THREAD

**Issue by miharbi1982** [wilkelab/ggtext#32]
Hi Wilke;
There're a problem when I installing the ggtext package. The message error is :
Warning message:
package ‘ggtext’ is not available (for R version 3.6.3)
Any solution plz?

**Comment by thomas-neitmann** [comment]
The package is not yet available from CRAN. You can install it from GitHub using `remotes::install_github("wilkelab/ggtext")`.

**Comment by miharbi1982** [comment]
Yes, it's fixed.
Thanks a lot!
