### ISSUE TITLE
opacity

### ISSUE THREAD

**Issue by SteffenMoritz** [wilkelab/ggtext#41]
A very short question:
I tried using opacity in my html code. 
Is this supported and I just did something wrong?

I didn't see it in any ggtext documentation - if not already possible it would be a great addition to future versions.

Great package!

**Comment by SteffenMoritz** [comment]
Ok ... no idea, if the command `opacity: 0.5` is actually supported. But I solved it anyway - I just used an 8 Digit Hex Color, e.g. `style='color:#ee636322;'` which gives the same result.

**Comment by clauswilke** [comment]
For any feature you may think of, if it's not used in any example in the documentation, most likely it's not supported. I'll most likely support more CSS features in the future, but it'll require a lot of infrastructure work first.

**Comment by clauswilke** [comment]
See #53.
