### ISSUE TITLE
vectorized box_width in geom_textbox

### ISSUE THREAD

**Issue by higgi13425** [wilkelab/ggtext#43]
At times with geom_textbox,
it would be helpful to have more control of the width of each line in each box, and to be able to make some boxes quite wide, and others more narrow. 
Currently geom_textbox seems to arbitrarily decide when to put in line breaks to produce even line lengths, which makes textboxes that are wide and not very tall impossible. 

Alternatively, to have an option to be able to assign to all boxes an option to **never** wrap lines unless there is a <br> could also work.

```r
# insert reprex here
```

**Comment by clauswilke** [comment]
See #53.
