### ISSUE TITLE
element_markdown() makes my title jump.

### ISSUE THREAD

**Issue by bersbersbers** [wilkelab/ggtext#44]
Do I need to say more? ;)

![animation_test](https://user-images.githubusercontent.com/12128514/87771164-4a57d400-c820-11ea-9203-3cb4bb3d9b9a.gif)

```r
library(ggplot2)
library(ggtext)
library(gganimate)
library(magick)
plot <- ggplot(data.frame(step = 1:3), aes(x = step, y = step)) +
    ggtitle("({frame}/9) Hi there. I should not be jumping like this!") +
    theme(plot.title = element_markdown()) +
    transition_manual(step)
anim <- animate(plot, renderer = function(frames, fps) {
    pngs <- image_read(frames)
    gifs <- image_animate(pngs, dispose = "previous")
    image_write(gifs, "animation_test.gif")
})
```

![animation_test](https://user-images.githubusercontent.com/12128514/87771278-6fe4dd80-c820-11ea-8876-42c76c15888e.gif)

```r
library(ggplot2)
library(ggtext)
library(gganimate)
library(magick)
plot <- ggplot(data.frame(step = 1:3), aes(x = step, y = step)) +
    ggtitle("({frame}/9) Hi there. Without element_markdown, I stand still!") +
    # theme(plot.title = element_markdown()) +
    transition_manual(step)
anim <- animate(plot, renderer = function(frames, fps) {
    pngs <- image_read(frames)
    gifs <- image_animate(pngs, dispose = "previous")
    image_write(gifs, "animation_test.gif")
})
```

**Comment by clauswilke** [comment]
This is probably due to rounding errors because ggtext breaks down the test into individual pieces and calculates where they should be placed. Try to render this at a higher resolution and see if it gets better.

If it is due to rounding errors, there isn't much I can do at this time.

**Comment by bersbersbers** [comment]
> This is probably due to rounding errors because ggtext breaks down the test into individual pieces and calculates where they should be placed.

Thanks - this explains why the second part jumps around while the first one remains pixel-perfect. I'm already at a quite high resolution - what I did was to *lower* the resolution, which fixed the issue for now.

**Comment by bersbersbers** [comment]
@clauswilke 
> If it is due to rounding errors, there isn't much I can do at this time.

Could you point me to the place in the code where this rounding occurs? I imagine that these individual pieces are placed based on where each previous piece (generally, the one left of it) is placed. If that is the case, I'd think that one should be compute the rounding error of each piece and propagate it to the next element to maybe solve this issue.

**Comment by clauswilke** [comment]
This should be fixed once we switch over to the sinab rendering engine, because it doesn't break strings into pieces unless needed for formatting changes. See #53.
