### ISSUE TITLE
Using diaeresis/tréma/umlaut in title causing unintended extra whitespace

### ISSUE THREAD

**Issue by msberends** [wilkelab/ggtext#49]
Thanks for this package!

I notice that when using a diaeresis (e.g. ë), the title gets additional whitespace after the word that contains it:

```r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  labs(title = "Test with ë diaeresis") +
  theme(plot.title = element_markdown())
```

![image](https://user-images.githubusercontent.com/31037261/93452808-29236a80-f8d9-11ea-9687-fb741121515b.png)

**Comment by clauswilke** [comment]
See #19.

**Comment by msberends** [comment]
Alright, but my problems are gone if I don’t use `element_markdown()`. I’ll continue on issue #19 for this. 

Thanks!
