### ISSUE TITLE
Support for "code" Markdown

### ISSUE THREAD

**Issue by asolisc** [wilkelab/ggtext#52]
Hi Mr. Wilke,

First of all, thank you so much for the amazing ggtext! Certainly an amazing step in the right direction. I was trying to insert a "code" markdown in the title of the ggplot2 but apparently, ggtext doesn't support it yet?

Please find below the reprex.

Best,
Alexis

``` r
library(ggtext)
library(tidyverse)

mpg %>% 
  ggplot(mapping = aes(x = displ)) +
  geom_bar(fill = "#13364C") +
  labs(
    title = "This is a `geom_bar()` plot"
  )  +
  theme(
    plot.title = element_markdown()
  )
#> Error: gridtext has encountered a tag that isn't supported yet: <code>
#> Only a very limited number of tags are currently supported.
```

![](https://i.imgur.com/xp60S54.png)

<sup>Created on 2020-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
See #53.
