### ISSUE TITLE
{stringr} str_wrap not working on element_markdown() text

### ISSUE THREAD

**Issue by jesadrperez** [wilkelab/ggtext#56]
Hello,

I can no longer use `stringr::str_wrap() `on text that has `ggtext::element_markdown()` applied to it.

``` r
library(ggplot2)
library(ggtext)
library(stringr)

# Basic Plot
ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  ggtitle("The data was extracted from the 1974 Motor Trend US magazine.")
```

![](https://i.imgur.com/WL2Ftij.png)

``` r

# Plot with str_wrap
ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  ggtitle(str_wrap("The data was extracted from the 1974 Motor Trend US magazine.", width = 50))
```

![](https://i.imgur.com/KX3KqMb.png)

``` r

# Plot with str_wrap and ggtext
ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  ggtitle(str_wrap("The data was extracted from the 1974 Motor Trend US magazine.", width = 50)) +
  theme(plot.title = element_markdown())
```

![](https://i.imgur.com/rdfwyAJ.png)

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Yes, markdown absorbs newlines. You could use `gsub()` to replace `\n` with `<br>`, or you could use `element_textbox()` to let it handle the word wrapping. In my opinion, the second option makes more sense.
