### ISSUE TITLE
How to centre align text in geom_textbox()?

### ISSUE THREAD

**Issue by barrel0luck** [wilkelab/ggtext#57]
This is not an issue report per se, but just that I'm not managing to figure out how to do this. I tried using centre align tags of markdown and html (using escape character for quotes) but I can't figure out how to centre align text in geom_textbox(). It's probably because I'm not an expert in markdown/ html. Can you tell me what tag I need to use to centre align the text?

**Comment by clauswilke** [comment]
Please ask these types of questions on Stackoverflow or the RStudio Community.

**Comment by barrel0luck** [comment]
Sorry for the spam here, but since your package is new I did not think anyone but you would know the answer. It's fine if you don't want to help.

**Comment by clauswilke** [comment]
As a reminder, to file this issue, you had to delete the following text, which explains in detail when and how to use the issue system:

Issues are meant to report bugs or request features. If you have questions about how to correctly use this package, please don't use the issue system. Such questions can be asked on stackoverflow https://stackoverflow.com/ or the RStudio community https://community.rstudio.com/. If you are not sure where to go, please try https://stackoverflow.com/ first.

Issues must contain reproducible code examples. Please use the reprex package to create your example (see here: http://reprex.tidyverse.org/). Issues without reprex may be closed without comment.

Please delete these instructions after you have read them.

------

Brief description of the problem or desired feature.

```r
# insert reprex here
```
