### ISSUE TITLE
Problem with text spacing (when using PDF device)

### ISSUE THREAD

**Issue by PMassicotte** [wilkelab/ggtext#58]
First, thank you for the great package.

I am trying to make a graph using the `ggtext` package. I found out that the spacing between characters is off  when I am saving the graphic using the PDF cairo device (I do not have this problem when saving to PNG).

``` r
library(tidyverse)
library(ggtext)
library(glue)
#> 
#> Attaching package: 'glue'
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse

canada <- rnaturalearth::ne_states("canada", returnclass = "sf")

canada <- canada %>% 
  mutate(label = glue::glue("{sov_a3}<br><span style = 'font-size:4pt;'>{admin} 123456789</span>"))

ggplot() +
  geom_sf(data = canada) +
  facet_wrap(~label) +
  theme(
    strip.text = element_markdown(family = "Poppins")
  )
```
This is ok:

![](https://i.imgur.com/Ay08G1U.png)

``` r
ggsave("~/Desktop/test.pdf", device = cairo_pdf)
#> Saving 7 x 5 in image
```

When saving using the PDF device, the spacing is wrong:

![image](https://user-images.githubusercontent.com/4519221/101351727-04e38400-385f-11eb-9250-bfc4b77e48e1.png)

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by clauswilke** [comment]
Looks like Cairo doesn't know the font you're using. That's not a ggtext issue.

**Comment by PMassicotte** [comment]
It looks like the problem is related with the font size.

``` r
library(tidyverse)
library(ggtext)
library(glue)
#> 
#> Attaching package: 'glue'
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse

ggplot() +
  annotate(
    "text",
    x = 1,
    y = 1,
    label = "123456789",
    family = "Poppins"
  ) +
  annotate(
    "richtext",
    x = 2,
    y = 1,
    label = "<span>123456789</span>",
    family = "Poppins",
    fill = NA,
    label.color = NA
  ) + 
  annotate(
    "richtext",
    x = 2,
    y = 0.975,
    label = glue::glue("<span style = 'font-size:10pt;'>123456789</span>"),
    family = "Poppins",
    fill = NA,
    label.color = NA
  ) +
  annotate(
    "richtext",
    x = 2,
    y = 0.976,
    label = glue::glue("<span style = 'font-size:4pt;'>123456789</span>"),
    family = "Poppins",
    fill = NA,
    label.color = NA
  ) +
  scale_x_continuous(expand = expansion(mult = c(1, 1)))
```

![](https://i.imgur.com/dhaIJbR.png)

``` r
ggsave("~/Desktop/test.pdf", device = cairo_pdf)

```
If we zoom in, we see that the problem occurs when the font size if small.

![image](https://user-images.githubusercontent.com/4519221/101392059-3ece7d80-3893-11eb-8747-21709a423217.png)

Should I open an issue elsewhere?

<sup>Created on 2020-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by clauswilke** [comment]
I would start with a posting on stackoverflow. Somebody may know of a way of fixing the issue.

**Comment by PMassicotte** [comment]
Thank you. As you said, probably not related to {ggtext}. I will close it. For reference:

https://stackoverflow.com/questions/65188058/font-spacing-whern-using-cairo-pdf-device

Thank you for your time.

**Comment by PMassicotte** [comment]
Regarding your stack comment about size, do you mean:

```r
ggplot() +
    annotate(
      "richtext",
      x = 0,
      y = 1,
      label = "<span style = 'font-size:4pt;'>123456789</span>",
      family = "Poppins",
      fill = NA,
      label.color = NA
    ) +
    geom_text(
      aes(
        x = 0,
        y = 1.01
      ),
      label = "123456789",
      family = "Poppins",
      size = 12 / 4
    ) +
    scale_y_continuous(expand = expansion(mult = c(1, 1)))
```

Doing that still create differences in size.
