### ISSUE TITLE
letters are overlapping when using ggtext & ggiraph on mobile device

### ISSUE THREAD

**Issue by werkstattcodes** [wilkelab/ggtext#62]
I am trying to produce a plot using ggplot, ggtext, and ggiraph. The plot title should contain some words in color.
The code below works fine as long as I look at the produced graph on a larger screen (laptop is ok). When I look at it on a mobile device, the letters are overlapping.

I tried to isolate the problem and put it online [here](https://distill-test-drive.netlify.app/post/2021-03-16-ggiraph-ggtext-problem/): 

I had also put on a related SO question, but to no avail. Many thanks.

```{r}
library(ggtext)
library(ggiraph)
library(tidyverse)

my_plot <- mtcars %>% 
  ggplot()+
  labs(title=glue::glue("this is a very long title, with many lines and a line <br>break etc etc etc, this <br>word is in <span style='color:red;'>red</span> or something else etc etc"))+
  geom_point_interactive(aes(x=wt,
                             y=qsec,
                             tooltip=paste(wt, qsec)))+
   theme(plot.title=element_markdown())

girafe(ggobj = my_plot,
       fonts=list(sans="Roboto Condensed"),
       height_svg = 5,
       options = list(
         opts_toolbar(saveaspng = FALSE))
)
```

Screenshot from laptop:
![laptop_screenshot](https://user-images.githubusercontent.com/9595585/111608206-3f9f7580-87d9-11eb-9868-80be953d6538.png)

Screenshot from mobile device:
![mobile_screenshot](https://user-images.githubusercontent.com/9595585/111608515-95741d80-87d9-11eb-9534-86b5c1b46b23.png)

**Comment by sbaross** [comment]
I'm having a similar issue that occurs when I try to save my plot with ggsave() - the plot appears fine within RStudio. In my case it seems to specifically happen with plots I've arranged using cowplot, the individual plots save fine but if I save the multi-plot grid the words in the element_markdown() elements overlap as seen here. I'm not using ggiraph so I think this is a ggtext issue.

**Comment by bwiernik** [comment]
Install the latest version of *gridtext* from https://github.com/wilkelab/gridtext. It should be on CRAN soon.
