### ISSUE TITLE
element_markdown() does not work when facet_wrap(strip.position = "left")

### ISSUE THREAD

**Issue by graco-roza** [wilkelab/ggtext#63]
I have read all the discussion on the use of HTML code with {glue}, {ggtext} and {ggplot2} in the facet titles using ggplot and `
element_markdown()`, then I manage to use the example given by @clauswilke  to generate the plot
```r
library(tidyverse)
library(glue)
#> 
#> Attaching package: 'glue'
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse
library(ggtext)

count(mtcars, cyl, carb) %>% 
  mutate(cyl_lab = as.character(
    glue("Cylinders {cyl} <span style='color:red'>(n={n})</span>")
  )) %>% 
  ggplot(aes(carb, n)) +
  geom_col() +
  facet_wrap(~cyl_lab) +
  theme(
    strip.text = element_markdown(),
    strip.text.x = element_markdown(),
    strip.text.y = element_markdown()
```
![Rplot](https://user-images.githubusercontent.com/61427460/112965938-699a5580-9152-11eb-81c4-92c38044d0ea.png)

However, when applying `strip.position = "left"` or even `switch = "y"` in the facet function, the plot does not format the HTML code.

```r
library(tidyverse)
library(glue)
#> 
#> Attaching package: 'glue'
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse
library(ggtext)

count(mtcars, cyl, carb) %>% 
  mutate(cyl_lab = as.character(
    glue("Cylinders {cyl} <span style='color:red'>(n={n})</span>")
  )) %>% 
  ggplot(aes(carb, n)) +
  geom_col() +
  facet_wrap(~cyl_lab, strip.position = "left") +
  theme(
    strip.text = element_markdown(),
    strip.text.x = element_markdown(),
    strip.text.y = element_markdown()
```
![error-Rplot01](https://user-images.githubusercontent.com/61427460/112965964-6ef7a000-9152-11eb-8925-66f63d94aa10.png)

I searched for similar issues here but I couldn't find any. Also, if this is something related to the wrong use of functions I apologize in advance.

**Comment by clauswilke** [comment]
See here: https://github.com/wilkelab/ggtext/issues/5#issuecomment-539155038
Same problem.
