### ISSUE TITLE
Markdown text is not displayed if the string begins with a percent symbol ("%")

### ISSUE THREAD

**Issue by goaltergeist** [wilkelab/ggtext#67]
Hello, thank you for this amazing package. I am encountering a behavior where `element_markdown()` doesn't render `ggplot2` labels if the label string begins with a percent symbol, i.e. `%`.

A plot with working x axis label and title, formatted in Markdown:
```r
library(tidyverse)
library(ggtext)
mtcars %>%
    ggplot(aes(mpg, cyl/8, color = am)) +
    geom_point() +
    labs(title = "A working _ggtext_ **markdown** title.") +
    scale_x_continuous(name = "Percent of Maximum **Cylinders** (8)") +
    theme(plot.title = element_markdown(), axis.title.x = element_markdown())
```

![image](https://user-images.githubusercontent.com/85708360/125344630-89324400-e325-11eb-9615-10da364a8a01.png)

The same plot, but this x axis label doesn't print as it begins with `%`:
```r
library(tidyverse)
library(ggtext)
mtcars %>%
    ggplot(aes(mpg, cyl/8, color = am)) +
    geom_point() +
    labs(title = "A working _ggtext_ **markdown** title.") +
    scale_x_continuous(name = "% of Maximum **Cylinders** (8)") +
    theme(plot.title = element_markdown(), axis.title.x = element_markdown())
```

![image](https://user-images.githubusercontent.com/85708360/125344695-9bac7d80-e325-11eb-9b64-3c4e427fc54d.png)

If `axis.title.x` is set to `element_text()`, the label beginning with `%` is displayed:
```r
library(tidyverse)
library(ggtext)
mtcars %>%
    ggplot(aes(mpg, cyl/8, color = am)) +
    geom_point() +
    labs(title = "A working _ggtext_ **markdown** title.") +
    scale_x_continuous(name = "% of Maximum **Cylinders** (8)") +
    theme(plot.title = element_markdown(), axis.title.x = element_text())
```

![image](https://user-images.githubusercontent.com/85708360/125344788-b54dc500-e325-11eb-9744-4cd05ed72e40.png)

Lastly, escaping the percent symbol does not work because the `\` is escaped rather than the `%`:
```r
library(tidyverse)
library(ggtext)
mtcars %>%
    ggplot(aes(mpg, cyl/8, color = am)) +
    geom_point() +
    labs(title = "A working _ggtext_ **markdown** title.") +
    scale_x_continuous(name = "\\% of Maximum **Cylinders** (8)") +
    theme(plot.title = element_markdown(), axis.title.x = element_markdown())
```

![image](https://user-images.githubusercontent.com/85708360/125345384-779d6c00-e326-11eb-9a42-f90b04686d22.png)

Is there any way for a label string to begin with `%`?

**Comment by clauswilke** [comment]
Use the html entity, `&#37;`.

``` r
library(tidyverse)
library(ggtext)
mtcars %>%
  ggplot(aes(mpg, cyl/8, color = am)) +
  geom_point() +
  labs(title = "A working _ggtext_ **markdown** title.") +
  scale_x_continuous(name = "&#37; of Maximum **Cylinders** (8)") +
  theme(plot.title = element_markdown(), axis.title.x = element_markdown())
```

![](https://i.imgur.com/8PNhkaZ.png)

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
