### ISSUE TITLE
Vertical alignment of the box surrounding the figure title text

### ISSUE THREAD

**Issue by gulinan** [wilkelab/ggtext#69]
Hi,

In the following reproducible example, I would like to move the surrounding box of figure title down, specifically, to the center of the figure. I tried our several positive/negative values of vertical adjustment, namely,  ```vjust```, however it did not work out. I wonder what I am missing here. I would really appreciate your suggestion.

------

Brief description of the problem or desired feature.

```r
library(ggplot2)
library(ggtext)


data <- data.frame(
  name=c("A","B","C","D","E") ,
  value=c(3,12,5,18,45)
)

ggplot(data, aes(x=name, y=value, fill = "name")) +
  geom_col()+
  ggtitle("Figure Title <br><b><i>Comes Here </b></i>")+
  theme(plot.title.position = "panel",
        plot.title = element_textbox_simple(width = grid::unit(1.2, "in"),
                                            fill = "black",
                                            size = 12, 
                                            color ="blue", 
                                            halign = 0.5, 
                                            hjust  = 0.5, 
                                            vjust  = -10) ))

```

![Rplot](https://user-images.githubusercontent.com/56047198/129493983-9a693111-3595-4d6c-be05-b0e9b95ae53c.jpeg)

**Comment by clauswilke** [comment]
Please ask these types of questions on stackoverflow or the RStudio community.
